language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-py-tox' ]; then cd .. && eval "mv $currentfolder generator-py-tox" && cd generator-py-tox; fi

